package dto;

public class Cv {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cv.id
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cv.cvsex
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    private String cvsex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cv.cvclass
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    private String cvclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cv.cvnumber
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    private String cvnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cv.cvmajor
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    private String cvmajor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cv.cvtellphone
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    private String cvtellphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cv.cvemail
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    private String cvemail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cv.cvqq
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    private String cvqq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cv.id
     *
     * @return the value of cv.id
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cv.id
     *
     * @param id the value for cv.id
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cv.cvsex
     *
     * @return the value of cv.cvsex
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    public String getCvsex() {
        return cvsex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cv.cvsex
     *
     * @param cvsex the value for cv.cvsex
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    public void setCvsex(String cvsex) {
        this.cvsex = cvsex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cv.cvclass
     *
     * @return the value of cv.cvclass
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    public String getCvclass() {
        return cvclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cv.cvclass
     *
     * @param cvclass the value for cv.cvclass
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    public void setCvclass(String cvclass) {
        this.cvclass = cvclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cv.cvnumber
     *
     * @return the value of cv.cvnumber
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    public String getCvnumber() {
        return cvnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cv.cvnumber
     *
     * @param cvnumber the value for cv.cvnumber
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    public void setCvnumber(String cvnumber) {
        this.cvnumber = cvnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cv.cvmajor
     *
     * @return the value of cv.cvmajor
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    public String getCvmajor() {
        return cvmajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cv.cvmajor
     *
     * @param cvmajor the value for cv.cvmajor
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    public void setCvmajor(String cvmajor) {
        this.cvmajor = cvmajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cv.cvtellphone
     *
     * @return the value of cv.cvtellphone
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    public String getCvtellphone() {
        return cvtellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cv.cvtellphone
     *
     * @param cvtellphone the value for cv.cvtellphone
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    public void setCvtellphone(String cvtellphone) {
        this.cvtellphone = cvtellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cv.cvemail
     *
     * @return the value of cv.cvemail
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    public String getCvemail() {
        return cvemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cv.cvemail
     *
     * @param cvemail the value for cv.cvemail
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    public void setCvemail(String cvemail) {
        this.cvemail = cvemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cv.cvqq
     *
     * @return the value of cv.cvqq
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    public String getCvqq() {
        return cvqq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cv.cvqq
     *
     * @param cvqq the value for cv.cvqq
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    public void setCvqq(String cvqq) {
        this.cvqq = cvqq;
    }
}