package dto;

public class CvWithBLOBs extends Cv {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cv.cvexperience
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    private String cvexperience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cv.cvresult
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    private String cvresult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cv.cvother
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    private String cvother;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cv.cvexperience
     *
     * @return the value of cv.cvexperience
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    public String getCvexperience() {
        return cvexperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cv.cvexperience
     *
     * @param cvexperience the value for cv.cvexperience
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    public void setCvexperience(String cvexperience) {
        this.cvexperience = cvexperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cv.cvresult
     *
     * @return the value of cv.cvresult
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    public String getCvresult() {
        return cvresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cv.cvresult
     *
     * @param cvresult the value for cv.cvresult
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    public void setCvresult(String cvresult) {
        this.cvresult = cvresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cv.cvother
     *
     * @return the value of cv.cvother
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    public String getCvother() {
        return cvother;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cv.cvother
     *
     * @param cvother the value for cv.cvother
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    public void setCvother(String cvother) {
        this.cvother = cvother;
    }
}