package dto;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.password
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    private String password;

    public String getGrade() {
        return grade;
    }

    public void setGrade(String grade) {
        this.grade = grade;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.class
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    private String grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.tellphone
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    private String tellphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.qq
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.email
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.cvid
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    private Long cvid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sex
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    private String sex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.password
     *
     * @return the value of student.password
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.password
     *
     * @param password the value for student.password
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.tellphone
     *
     * @return the value of student.tellphone
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    public String getTellphone() {
        return tellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.tellphone
     *
     * @param tellphone the value for student.tellphone
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    public void setTellphone(String tellphone) {
        this.tellphone = tellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.qq
     *
     * @return the value of student.qq
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.qq
     *
     * @param qq the value for student.qq
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.email
     *
     * @return the value of student.email
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.email
     *
     * @param email the value for student.email
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.cvid
     *
     * @return the value of student.cvid
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    public Long getCvid() {
        return cvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.cvid
     *
     * @param cvid the value for student.cvid
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    public void setCvid(Long cvid) {
        this.cvid = cvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sex
     *
     * @return the value of student.sex
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sex
     *
     * @param sex the value for student.sex
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    public void setSex(String sex) {
        this.sex = sex;
    }
}