package dto;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbggenerated Tue Aug 09 16:52:26 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbggenerated Tue Aug 09 16:52:26 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.password
     *
     * @mbggenerated Tue Aug 09 16:52:26 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.numbersum
     *
     * @mbggenerated Tue Aug 09 16:52:26 CST 2016
     */
    private Integer numbersum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.number
     *
     * @mbggenerated Tue Aug 09 16:52:26 CST 2016
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.tearcherid
     *
     * @mbggenerated Tue Aug 09 16:52:26 CST 2016
     */
    private Long tearcherid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.isselect
     *
     * @mbggenerated Tue Aug 09 16:52:26 CST 2016
     */
    private Boolean isselect;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbggenerated Tue Aug 09 16:52:26 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbggenerated Tue Aug 09 16:52:26 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbggenerated Tue Aug 09 16:52:26 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbggenerated Tue Aug 09 16:52:26 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.password
     *
     * @return the value of student.password
     *
     * @mbggenerated Tue Aug 09 16:52:26 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.password
     *
     * @param password the value for student.password
     *
     * @mbggenerated Tue Aug 09 16:52:26 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.numbersum
     *
     * @return the value of student.numbersum
     *
     * @mbggenerated Tue Aug 09 16:52:26 CST 2016
     */
    public Integer getNumbersum() {
        return numbersum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.numbersum
     *
     * @param numbersum the value for student.numbersum
     *
     * @mbggenerated Tue Aug 09 16:52:26 CST 2016
     */
    public void setNumbersum(Integer numbersum) {
        this.numbersum = numbersum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.number
     *
     * @return the value of student.number
     *
     * @mbggenerated Tue Aug 09 16:52:26 CST 2016
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.number
     *
     * @param number the value for student.number
     *
     * @mbggenerated Tue Aug 09 16:52:26 CST 2016
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.tearcherid
     *
     * @return the value of student.tearcherid
     *
     * @mbggenerated Tue Aug 09 16:52:26 CST 2016
     */
    public Long getTearcherid() {
        return tearcherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.tearcherid
     *
     * @param tearcherid the value for student.tearcherid
     *
     * @mbggenerated Tue Aug 09 16:52:26 CST 2016
     */
    public void setTearcherid(Long tearcherid) {
        this.tearcherid = tearcherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.isselect
     *
     * @return the value of student.isselect
     *
     * @mbggenerated Tue Aug 09 16:52:26 CST 2016
     */
    public Boolean getIsselect() {
        return isselect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.isselect
     *
     * @param isselect the value for student.isselect
     *
     * @mbggenerated Tue Aug 09 16:52:26 CST 2016
     */
    public void setIsselect(Boolean isselect) {
        this.isselect = isselect;
    }
}