package dto;

public class StuTea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_tea.studentid
     *
     * @mbggenerated Sun Aug 28 19:41:37 CST 2016
     */
    private Long studentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_tea.teacherid
     *
     * @mbggenerated Sun Aug 28 19:41:37 CST 2016
     */
    private Long teacherid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_tea.listnumber
     *
     * @mbggenerated Sun Aug 28 19:41:37 CST 2016
     */
    private Integer listnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_tea.number
     *
     * @mbggenerated Sun Aug 28 19:41:37 CST 2016
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_tea.isselect
     *
     * @mbggenerated Sun Aug 28 19:41:37 CST 2016
     */
    private Boolean isselect;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_tea.studentid
     *
     * @return the value of stu_tea.studentid
     *
     * @mbggenerated Sun Aug 28 19:41:37 CST 2016
     */
    public Long getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_tea.studentid
     *
     * @param studentid the value for stu_tea.studentid
     *
     * @mbggenerated Sun Aug 28 19:41:37 CST 2016
     */
    public void setStudentid(Long studentid) {
        this.studentid = studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_tea.teacherid
     *
     * @return the value of stu_tea.teacherid
     *
     * @mbggenerated Sun Aug 28 19:41:37 CST 2016
     */
    public Long getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_tea.teacherid
     *
     * @param teacherid the value for stu_tea.teacherid
     *
     * @mbggenerated Sun Aug 28 19:41:37 CST 2016
     */
    public void setTeacherid(Long teacherid) {
        this.teacherid = teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_tea.listnumber
     *
     * @return the value of stu_tea.listnumber
     *
     * @mbggenerated Sun Aug 28 19:41:37 CST 2016
     */
    public Integer getListnumber() {
        return listnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_tea.listnumber
     *
     * @param listnumber the value for stu_tea.listnumber
     *
     * @mbggenerated Sun Aug 28 19:41:37 CST 2016
     */
    public void setListnumber(Integer listnumber) {
        this.listnumber = listnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_tea.number
     *
     * @return the value of stu_tea.number
     *
     * @mbggenerated Sun Aug 28 19:41:37 CST 2016
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_tea.number
     *
     * @param number the value for stu_tea.number
     *
     * @mbggenerated Sun Aug 28 19:41:37 CST 2016
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_tea.isselect
     *
     * @return the value of stu_tea.isselect
     *
     * @mbggenerated Sun Aug 28 19:41:37 CST 2016
     */
    public Boolean getIsselect() {
        return isselect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_tea.isselect
     *
     * @param isselect the value for stu_tea.isselect
     *
     * @mbggenerated Sun Aug 28 19:41:37 CST 2016
     */
    public void setIsselect(Boolean isselect) {
        this.isselect = isselect;
    }
}