package dto;

public class System {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system.marksum
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    private Integer marksum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system.usernumber
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    private Integer usernumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system.teacherselect
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    private Integer teacherselect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system.studentselect
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    private Integer studentselect;

    public String getAdvice() {
        return advice;
    }

    public void setAdvice(String advice) {
        this.advice = advice;
    }

    private String advice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system.marksum
     *
     * @return the value of system.marksum
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    public Integer getMarksum() {
        return marksum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system.marksum
     *
     * @param marksum the value for system.marksum
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    public void setMarksum(Integer marksum) {
        this.marksum = marksum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system.usernumber
     *
     * @return the value of system.usernumber
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    public Integer getUsernumber() {
        return usernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system.usernumber
     *
     * @param usernumber the value for system.usernumber
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    public void setUsernumber(Integer usernumber) {
        this.usernumber = usernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system.teacherselect
     *
     * @return the value of system.teacherselect
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    public Integer getTeacherselect() {
        return teacherselect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system.teacherselect
     *
     * @param teacherselect the value for system.teacherselect
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    public void setTeacherselect(Integer teacherselect) {
        this.teacherselect = teacherselect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system.studentselect
     *
     * @return the value of system.studentselect
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    public Integer getStudentselect() {
        return studentselect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system.studentselect
     *
     * @param studentselect the value for system.studentselect
     *
     * @mbggenerated Sun Aug 28 19:34:11 CST 2016
     */
    public void setStudentselect(Integer studentselect) {
        this.studentselect = studentselect;
    }
}