package dto;

public class System {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system.marksum
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    private Integer marksum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system.usernumber
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    private Integer usernumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system.selectnumber
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    private Integer selectnumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system.marksum
     *
     * @return the value of system.marksum
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    public Integer getMarksum() {
        return marksum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system.marksum
     *
     * @param marksum the value for system.marksum
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    public void setMarksum(Integer marksum) {
        this.marksum = marksum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system.usernumber
     *
     * @return the value of system.usernumber
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    public Integer getUsernumber() {
        return usernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system.usernumber
     *
     * @param usernumber the value for system.usernumber
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    public void setUsernumber(Integer usernumber) {
        this.usernumber = usernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system.selectnumber
     *
     * @return the value of system.selectnumber
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    public Integer getSelectnumber() {
        return selectnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system.selectnumber
     *
     * @param selectnumber the value for system.selectnumber
     *
     * @mbggenerated Mon Aug 08 17:17:01 CST 2016
     */
    public void setSelectnumber(Integer selectnumber) {
        this.selectnumber = selectnumber;
    }
}