package dto;

public class Teacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.id
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.name
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.password
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.sex
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.xueli
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    private String xueli;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.xuewei
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    private String xuewei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.position
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.duty
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    private String duty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.schoolage
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    private String schoolage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.tellphone
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    private String tellphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.email
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.qq
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.campus
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    private String campus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.cvid
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    private Long cvid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.islogin
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    private Boolean islogin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.id
     *
     * @return the value of teacher.id
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.id
     *
     * @param id the value for teacher.id
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.name
     *
     * @return the value of teacher.name
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.name
     *
     * @param name the value for teacher.name
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.password
     *
     * @return the value of teacher.password
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.password
     *
     * @param password the value for teacher.password
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.sex
     *
     * @return the value of teacher.sex
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.sex
     *
     * @param sex the value for teacher.sex
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.xueli
     *
     * @return the value of teacher.xueli
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    public String getXueli() {
        return xueli;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.xueli
     *
     * @param xueli the value for teacher.xueli
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    public void setXueli(String xueli) {
        this.xueli = xueli;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.xuewei
     *
     * @return the value of teacher.xuewei
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    public String getXuewei() {
        return xuewei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.xuewei
     *
     * @param xuewei the value for teacher.xuewei
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    public void setXuewei(String xuewei) {
        this.xuewei = xuewei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.position
     *
     * @return the value of teacher.position
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.position
     *
     * @param position the value for teacher.position
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.duty
     *
     * @return the value of teacher.duty
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    public String getDuty() {
        return duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.duty
     *
     * @param duty the value for teacher.duty
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    public void setDuty(String duty) {
        this.duty = duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.schoolage
     *
     * @return the value of teacher.schoolage
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    public String getSchoolage() {
        return schoolage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.schoolage
     *
     * @param schoolage the value for teacher.schoolage
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    public void setSchoolage(String schoolage) {
        this.schoolage = schoolage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.tellphone
     *
     * @return the value of teacher.tellphone
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    public String getTellphone() {
        return tellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.tellphone
     *
     * @param tellphone the value for teacher.tellphone
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    public void setTellphone(String tellphone) {
        this.tellphone = tellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.email
     *
     * @return the value of teacher.email
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.email
     *
     * @param email the value for teacher.email
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.qq
     *
     * @return the value of teacher.qq
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.qq
     *
     * @param qq the value for teacher.qq
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.campus
     *
     * @return the value of teacher.campus
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    public String getCampus() {
        return campus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.campus
     *
     * @param campus the value for teacher.campus
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    public void setCampus(String campus) {
        this.campus = campus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.cvid
     *
     * @return the value of teacher.cvid
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    public Long getCvid() {
        return cvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.cvid
     *
     * @param cvid the value for teacher.cvid
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    public void setCvid(Long cvid) {
        this.cvid = cvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.islogin
     *
     * @return the value of teacher.islogin
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    public Boolean getIslogin() {
        return islogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.islogin
     *
     * @param islogin the value for teacher.islogin
     *
     * @mbggenerated Wed Sep 21 20:13:51 CST 2016
     */
    public void setIslogin(Boolean islogin) {
        this.islogin = islogin;
    }
}