package dto;

public class teaStu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tea_stu.teacherid
     *
     * @mbggenerated Tue Aug 09 16:52:26 CST 2016
     */
    private Long teacherid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tea_stu.studentid
     *
     * @mbggenerated Tue Aug 09 16:52:26 CST 2016
     */
    private Long studentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tea_stu.teacherid
     *
     * @return the value of tea_stu.teacherid
     *
     * @mbggenerated Tue Aug 09 16:52:26 CST 2016
     */
    public Long getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tea_stu.teacherid
     *
     * @param teacherid the value for tea_stu.teacherid
     *
     * @mbggenerated Tue Aug 09 16:52:26 CST 2016
     */
    public void setTeacherid(Long teacherid) {
        this.teacherid = teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tea_stu.studentid
     *
     * @return the value of tea_stu.studentid
     *
     * @mbggenerated Tue Aug 09 16:52:26 CST 2016
     */
    public Long getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tea_stu.studentid
     *
     * @param studentid the value for tea_stu.studentid
     *
     * @mbggenerated Tue Aug 09 16:52:26 CST 2016
     */
    public void setStudentid(Long studentid) {
        this.studentid = studentid;
    }
}